package com.wadpam.ricotta.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity Branch.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2011-09-07T19:29:36.183+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface BranchDao extends GeneratedBranchDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
